waypoints:
  - frame_id: "map"
    position: { x: -5.5, y: -3.8, z: 0.0 }
    orientation: { x: 0.0, y: 0.0, z: 0.0, w: 1.0 }
  - frame_id: "map"
    position: { x: -5.5, y: -0.7, z: 0.0 }
    orientation: { x: 0.0, y: 0.0, z: 0.0, w: 1.0 }
  - frame_id: "map"
    position: { x: -5.5, y: 2, z: 0.0 }
    orientation: { x: 0.0, y: 0.0, z: 0.0, w: 1.0 }
  - frame_id: "map"
    position: { x: -0.5, y: 3, z: 0.0 }
    orientation: { x: 0.0, y: 0.0, z: 0.0, w: 1.0 }
  - frame_id: "map"
    position: { x: 2.8, y: 3, z: 0.0 }
    orientation: { x: 0.0, y: 0.0, z: 0.0, w: 1.0 }